return {
	"stevearc/conform.nvim",
	event = { "BufWritePre" },
	cmd = { "ConformInfo" },
	opts = {
		formatters_by_ft = {
			lua             = { "stylua" },
			nix             = { "nixfmt" },
			python          = { "ruff_format", "ruff_organize_imports" },
			sh              = { "shfmt" },
			bash            = { "shfmt" },
			rust            = { "rustfmt" },
			go              = { "gofmt" },
			zig             = { "zigfmt" },
			java            = { "google-java-format" },
			toml            = { "taplo" },
			javascript      = { "prettierd", "prettier", stop_after_first = true },
			typescript      = { "prettierd", "prettier", stop_after_first = true },
			typescriptreact = { "prettierd", "prettier", stop_after_first = true },
			javascriptreact = { "prettierd", "prettier", stop_after_first = true },
			json            = { "prettierd", "prettier", stop_after_first = true },
			yaml            = { "prettierd", "prettier", stop_after_first = true },
			markdown        = { "prettierd", "prettier", stop_after_first = true },
			css             = { "prettierd", "prettier", stop_after_first = true },
			html            = { "prettierd", "prettier", stop_after_first = true },
		},
		format_on_save = {
			lsp_format = "fallback",
			timeout_ms = 1500,
		},
	},
}
